FROM ubuntu

RUN apt-get update && apt-get install -y \
        cmake \
        debhelper \
        devscripts \
        g++ \
        libavahi-compat-libdnssd-dev \
        libcurl4-openssl-dev \
        libegl1-mesa \
        libgdk-pixbuf2.0-dev \
        libgl1-mesa-glx \
        libglib2.0-dev \
        libnotify-dev \
        libqt5svg5-dev \
        libsodium-dev \
        libssl-dev \
        libsystemd-dev \
        libx11-dev \
        make \
        qtbase5-dev \
        qtcreator \
        qtdeclarative5-dev \
        qttools5-dev \
        xorg-dev \
    && rm -rf /var/lib/apt/lists/*
